INSERT INTO bairros (id, nome_bairro) VALUES
(gen_random_uuid(),'Ana Maria'),
(gen_random_uuid(),'Archimedes Naspolini'),
(gen_random_uuid(),'Área Rual de Criciúma'),
(gen_random_uuid(),'Argentina'),
(gen_random_uuid(),'Boa Vista'),
(gen_random_uuid(),'Bosque do Repouso'),
(gen_random_uuid(),'Brasília'),
(gen_random_uuid(),'Buenos Aires'),
(gen_random_uuid(),'Capão Bonito'),
(gen_random_uuid(),'Catarinense'),
(gen_random_uuid(),'Ceará'),
(gen_random_uuid(),'Centro'),
(gen_random_uuid(),'Cidade Mineira Nova'),
(gen_random_uuid(),'Cidade Mineira Velha'),
(gen_random_uuid(),'Colonial'),
(gen_random_uuid(),'Coloninha Zilli'),
(gen_random_uuid(),'Comerciário'),
(gen_random_uuid(),'Cristo Redentor'),
(gen_random_uuid(),'Cruzeiro do Sul'),
(gen_random_uuid(),'Dagostin'),
(gen_random_uuid(),'Demboski'),
(gen_random_uuid(),'Distrito Industrial'),
(gen_random_uuid(),'dos Imigrantes'),
(gen_random_uuid(),'Estaçãozinha'),
(gen_random_uuid(),'Fábio Silva'),
(gen_random_uuid(),'Imperatriz'),
(gen_random_uuid(),'Jardim Angélica'),
(gen_random_uuid(),'Jardim das Paineiras'),
(gen_random_uuid(),'Jardim Maristela'),
(gen_random_uuid(),'Jardim Montevidéu'),
(gen_random_uuid(),'Jardim União'),
(gen_random_uuid(),'Laranjinha'),
(gen_random_uuid(),'Liberdade'),
(gen_random_uuid(),'Linha Anta'),
(gen_random_uuid(),'Linha Batista'),
(gen_random_uuid(),'Linha Cabral'),
(gen_random_uuid(),'Lote Seis'),
(gen_random_uuid(),'Mãe Luzia'),
(gen_random_uuid(),'Maria Céu'),
(gen_random_uuid(),'Metropol'),
(gen_random_uuid(),'Michel'),
(gen_random_uuid(),'Milanese'),
(gen_random_uuid(),'Mina Brasil'),
(gen_random_uuid(),'Mina do Mato'),
(gen_random_uuid(),'Mina do Toco'),
(gen_random_uuid(),'Mina União'),
(gen_random_uuid(),'Monte Castelo'),
(gen_random_uuid(),'Morro Estevão'),
(gen_random_uuid(),'Nossa Senhora da Salete'),
(gen_random_uuid(),'Nossa Senhora do Carmo'),
(gen_random_uuid(),'Operária Nova'),
(gen_random_uuid(),'Paraíso'),
(gen_random_uuid(),'Pedro Zanivam'),
(gen_random_uuid(),'Pinheirinho'),
(gen_random_uuid(),'Pio Corrêa'),
(gen_random_uuid(),'Poço Um'),
(gen_random_uuid(),'Primeira Linha'),
(gen_random_uuid(),'Primeira Linha Pontilhão'),
(gen_random_uuid(),'Progresso'),
(gen_random_uuid(),'Promorar Vila Vitória'),
(gen_random_uuid(),'Próspera'),
(gen_random_uuid(),'Quarta Linha'),
(gen_random_uuid(),'Recanto Verde'),
(gen_random_uuid(),'Renascer'),
(gen_random_uuid(),'Rio Maina'),
(gen_random_uuid(),'Sangão'),
(gen_random_uuid(),'Santa Augusta'),
(gen_random_uuid(),'Santa Bárbara'),
(gen_random_uuid(),'Santa Catarina'),
(gen_random_uuid(),'Santa Luzia'),
(gen_random_uuid(),'Santo Antônio'),
(gen_random_uuid(),'São Cristóvão'),
(gen_random_uuid(),'São Defende'),
(gen_random_uuid(),'São Domingos'),
(gen_random_uuid(),'São Francisco'),
(gen_random_uuid(),'São João'),
(gen_random_uuid(),'São Luiz'),
(gen_random_uuid(),'São Marcos'),
(gen_random_uuid(),'São Roque'),
(gen_random_uuid(),'São Sebastião'),
(gen_random_uuid(),'São Simão'),
(gen_random_uuid(),'Tereza Cristina'),
(gen_random_uuid(),'Universitário'),
(gen_random_uuid(),'Vera Cruz'),
(gen_random_uuid(),'Verdinho'),
(gen_random_uuid(),'Vila Belmiro'),
(gen_random_uuid(),'Vila Floresta'),
(gen_random_uuid(),'Vila Floresta II'),
(gen_random_uuid(),'Vila Francesa'),
(gen_random_uuid(),'Vila Isabel'),
(gen_random_uuid(),'Vila Macarini'),
(gen_random_uuid(),'Vila Manaus'),
(gen_random_uuid(),'Vila Maria'),
(gen_random_uuid(),'Vila Miguel'),
(gen_random_uuid(),'Vila Nova Esperança'),
(gen_random_uuid(),'Vila Rica'),
(gen_random_uuid(),'Vila São José'),
(gen_random_uuid(),'Vila Selinger'),
(gen_random_uuid(),'Vila Visconde'),
(gen_random_uuid(),'Vila Zuleima'),
(gen_random_uuid(),'Wosocris')
ON CONFLICT (nome_bairro) DO NOTHING;