INSERT INTO bairros (id, nome_bairro) VALUES
(gen_random_uuid(),'Ana Maria'),
(gen_random_uuid(),'Argentina'),
(gen_random_uuid(),'Bairro 9'),
(gen_random_uuid(),'Boa Vista'),
(gen_random_uuid(),'Brasília'),
(gen_random_uuid(),'Catarinense'),
(gen_random_uuid(),'Ceará'),
(gen_random_uuid(),'Centro (Região Praça Nereu Ramos)'),
(gen_random_uuid(),'Centro (Av. Centenário - Região Rodoviária)'),
(gen_random_uuid(),'Cidade Mineira Nova'),
(gen_random_uuid(),'Cidade Mineira Velha'),
(gen_random_uuid(),'Cruzeiro do Sul'),
(gen_random_uuid(),'Dal Pont'),
(gen_random_uuid(),'Dagostin'),
(gen_random_uuid(),'Demboski'),
(gen_random_uuid(),'Estaçãozinha'),
(gen_random_uuid(),'HG'),
(gen_random_uuid(),'Imigrantes'),
(gen_random_uuid(),'Jardim Angélica'),
(gen_random_uuid(),'Jardim Esteves'),
(gen_random_uuid(),'Jardim Las Vegas'),
(gen_random_uuid(),'Jardim Maristela'),
(gen_random_uuid(),'Jardim Paineiras'),
(gen_random_uuid(),'Lote Seis'),
(gen_random_uuid(),'Maria Céu'),
(gen_random_uuid(),'Metropol'),
(gen_random_uuid(),'Michel'),
(gen_random_uuid(),'Milanese (Região Cemitério)'),
(gen_random_uuid(),'Milanese (Lado Pinheirinho Alto)'),
(gen_random_uuid(),'Mina Brasil'),
(gen_random_uuid(),'Mina do Mato'),
(gen_random_uuid(),'Monte Castelo'),
(gen_random_uuid(),'Morro Estevão'),
(gen_random_uuid(),'Nossa Senhora da Salete'),
(gen_random_uuid(),'Operária Nova'),
(gen_random_uuid(),'Ouro Negro'),
(gen_random_uuid(),'Pedro Zanivam'),
(gen_random_uuid(),'Pinheirinho Alto'),
(gen_random_uuid(),'Pinheirinho Baixo'),
(gen_random_uuid(),'Pio Corrêa'),
(gen_random_uuid(),'Primeira Linha'),
(gen_random_uuid(),'Próspera'),
(gen_random_uuid(),'Quarta Linha'),
(gen_random_uuid(),'Recanto Verde'),
(gen_random_uuid(),'Rio Maina'),
(gen_random_uuid(),'Sangão'),
(gen_random_uuid(),'Santa Augusta'),
(gen_random_uuid(),'Santa Bárbara'),
(gen_random_uuid(),'Santa Catarina'),
(gen_random_uuid(),'Santo Antônio'),
(gen_random_uuid(),'São Cristóvão'),
(gen_random_uuid(),'São Domingos'),
(gen_random_uuid(),'São João'),
(gen_random_uuid(),'São Luiz'),
(gen_random_uuid(),'São Simão'),
(gen_random_uuid(),'Universitário'),
(gen_random_uuid(),'Vera Cruz'),
(gen_random_uuid(),'Vila Floresta I'),
(gen_random_uuid(),'Vila Floresta II'),
(gen_random_uuid(),'Vila Francesa'),
(gen_random_uuid(),'Vila Isabel'),
(gen_random_uuid(),'Vila Macarini'),
(gen_random_uuid(),'Vila Rica'),
(gen_random_uuid(),'Vila São José'),
(gen_random_uuid(),'Vila Zuleima'),
(gen_random_uuid(),'Wosocris')
ON CONFLICT (nome_bairro) DO NOTHING;